### ISSUE TITLE
500 Internal server error.

### ISSUE THREAD

**Issue by veresjohnny** [boidushya/w3m-siwe#1]
Hi!

If i clone repo, and install, i got an error.

'''
Module not found "ethers"
'''

After install it 

''' 
yarn add ethers
'''

I run the dev server, added .env file, etc.

'''
I got an 500 internal server error. 
'''

I tried implmenet to nextjs app router, here i no have 500 error, but like here, i got every time an error mesage.
"signature declined"
But i no have other error messages in server side or console.

**Comment by boidushya** [comment]
Next.js app router steps are currently underway, about the server error issue, can you provide a screenshot of your code structure / a Minimum Reproducible Example?

**Comment by veresjohnny** [comment]
The server error 500 has been solved.
The problem was that:
Missing NEXTAUTH_SECRET.
